import { useCallback, useState, type KeyboardEvent } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { AnimatePresence, motion, useReducedMotion, type Variants } from "framer-motion";

import {
  BtnArrow,
  FramerTag,
  bodyCopy,
  bodyCopyStrong,
  borderSoft,
  btnOutlineOnDark,
  btnPrimary,
  engagePanelLead,
  engageStepCode,
  engageStepItem,
  engageStepsGrid,
  engageStepsShell,
  engageStepTitle,
  formatOperatingStrip,
  heroStandfirst,
  productsChoiceGrid,
  productsFormatColumn,
  productsPanelStack,
  productsProofGrid,
  productsProofItem,
  sectionActionsInline,
  sectionContentGrid,
  sectionHeadlineLead,
  sectionHeadline,
  sectionInner,
  sectionLabelHeadlineStack,
  sectionPanelLead,
  sectionShell,
  sectionSubheading,
  sectionZoneDividerNested,
  subsectionTitle,
  subsectionTitleMuted,
  surfaceCardPadding,
  textCardBody,
  textGhost,
  textLabel,
  textMeta,
  textSubtle,
  textValue,
} from "@/components/framer-section";
import { HeroAmbientImage, HeroScrollCue, ServicesHero } from "@/components/services-hero";
import productsHeroAmbient from "@/assets/products-hero-ambient.jpg";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { UnifiedCTA } from "@/components/unified-cta";
import { PageSectionDots } from "@/components/page-section-dots";
import { ScrollChapter } from "@/components/home-scroll-cinema";
import { buildPageHead } from "@/lib/seo";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/products/")({
  head: () => {
    const seo = buildPageHead({
      title: "Products — Sprint & Marathon | R—M",
      description: "Sprint from 4 weeks or Marathon from 2 months.",
      pathname: "/products",
    });
    return {
      meta: seo.meta,
      links: seo.links,
    };
  },
  component: ProductsPage,
});

const modes = {
  sprint: {
    tag: "Sprint",
    meta: "From 4 weeks · tactical retainer",
    tempo: "Defined push",
    fitSignal: "A raise, launch, or growth blocker needs a fast reset.",
    headline: "High-impact marketing for fast raises and tight deadlines.",
    summary:
      "Built for a defined push: a raise, launch, or one blocked part of growth that needs a fast reset.",
    lead: "Sprint is a focused engagement with a clear scope and hard deadline. We embed into your workflow, deploy target channel mix, and move fast. You get weekly deliverables and clear data within a flexible monthly setup. Best suited for early-stage founders, growth leads preparing for a raise, and teams with solid traction looking for a breakthrough.",
    cta: "Scope a sprint →",
    format: "Tactical retainer",
    bestFor: "A defined challenge",
    cadence: "Daily check-ins",
    output: "Fixed deliverables",
    proof: [
      {
        value: "$75 → $30",
        label: "CPL in 30 days",
        context: "Paid acquisition rebuilt within the first month",
      },
      {
        value: "2.7",
        label: "ROAS in the first month",
        context: "Through a locked channel test stack",
      },
      {
        value: "3×",
        label: "Daily lead volume",
        context: "While cutting CPA from $50 to $30",
      },
    ],
    deliverables: [
      {
        title: "Positioning audit & fix",
        body: "We read everything your market sees—landing pages, decks, ads, socials—and rewrite the core pitch that should be doing 80% of the heavy lifting.",
      },
      {
        title: "Channel test stack",
        body: "Three high-probability distribution bets, deployed together over a two-week cycle. Hypothesis, creative, copy, and success metrics fully locked before launch.",
      },
      {
        title: "Conversion system review",
        body: "End-to-end funnel teardown: from first impression to signed deal. We isolate the single choke-point costing you the most and clear it.",
      },
    ],
  },
  marathon: {
    tag: "Marathon",
    meta: "From 2 months · strategic partnership",
    tempo: "Embedded system",
    fitSignal: "You need an embedded partner shaping GTM over quarters, not a one-off project.",
    headline: "For founders building a category beyond a product.",
    summary:
      "Built for teams that need an embedded strategic partner shaping message, GTM, and channel system over time.",
    lead: "Marathon replaces the in-house growth function — strategy, positioning, and multi-channel execution as one embedded system. Built for Series A+ teams and scale-ups treating growth as a board-level priority.",
    cta: "Start a marathon →",
    format: "Strategic partnership",
    bestFor: "Full brand build or market entry",
    cadence: "Weekly / Monthly strategy sessions",
    output: "Brand / GTM strategy",
    proof: [
      {
        value: "2.3×",
        label: "Pipeline growth in 6 months",
        context: "Inbound more than doubled on a flat paid budget",
      },
      {
        value: "30–50%",
        label: "Of all MQLs",
        context: "Generated by organic search alone",
      },
      {
        value: "10% → 25%",
        label: "Brand awareness",
        context: "Built through systematic communication",
      },
    ],
    deliverables: [
      {
        title: "Market narrative architecture",
        body: "Your core message should never lose relevance. Every quarter, we analyze and update your positioning to match the current market reality.",
      },
      {
        title: "Finding new growth tracks",
        body: "Every month, we line up fresh channel and creative ideas. We track live performance, filter out the noise, and scale the top performers.",
      },
      {
        title: "Embedded strategic support",
        body: "Continuous C-level support for your launches, fundraises, and pivots. We operate inside your context, working alongside your core team.",
      },
    ],
  },
} as const;

type Mode = keyof typeof modes;

const modePanelVariants: Variants = {
  hidden: { opacity: 0, y: 10 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.26, ease: [0.22, 1, 0.36, 1] },
  },
  exit: {
    opacity: 0,
    y: -6,
    transition: { duration: 0.1, ease: [0.4, 0, 1, 1] },
  },
};

const MODE_PANEL_ID = "format-panel";

const productsPageDots = [
  { id: "products-top", label: "Intro" },
  { id: "format", label: "Formats" },
  { id: "compare", label: "Comparison" },
  { id: "cta", label: "Call" },
] as const;

const comparisonRows = [
  {
    label: "Format",
    sprint: modes.sprint.format,
    marathon: modes.marathon.format,
  },
  {
    label: "Best for",
    sprint: modes.sprint.bestFor,
    marathon: modes.marathon.bestFor,
  },
  {
    label: "Cadence",
    sprint: modes.sprint.cadence,
    marathon: modes.marathon.cadence,
  },
  {
    label: "Output",
    sprint: modes.sprint.output,
    marathon: modes.marathon.output,
  },
] as const;

const MODE_ORDER: Mode[] = ["sprint", "marathon"];

function FormatChoiceCards({ active, onChange }: { active: Mode; onChange: (mode: Mode) => void }) {
  const reduce = useReducedMotion();

  const handleKeyDown = useCallback(
    (event: KeyboardEvent<HTMLDivElement>) => {
      const index = MODE_ORDER.indexOf(active);
      if (index < 0) return;

      if (event.key === "ArrowRight" || event.key === "ArrowDown") {
        event.preventDefault();
        onChange(MODE_ORDER[(index + 1) % MODE_ORDER.length]);
      } else if (event.key === "ArrowLeft" || event.key === "ArrowUp") {
        event.preventDefault();
        onChange(MODE_ORDER[(index - 1 + MODE_ORDER.length) % MODE_ORDER.length]);
      }
    },
    [active, onChange],
  );

  return (
    <div
      role="radiogroup"
      aria-label="Choose engagement format"
      className={productsChoiceGrid}
      onKeyDown={handleKeyDown}
    >
      {MODE_ORDER.map((mode) => {
        const data = modes[mode];
        const isActive = active === mode;
        return (
          <button
            key={mode}
            type="button"
            id={`mode-tab-${mode}`}
            role="radio"
            aria-checked={isActive}
            aria-controls={MODE_PANEL_ID}
            onClick={() => onChange(mode)}
            className={cn(
              "rm-format-choice rm-touch cursor-pointer text-left",
              "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/25 focus-visible:ring-offset-4 focus-visible:ring-offset-[var(--rm-surface-raised)]",
              !reduce && "motion-safe:active:scale-[0.99]",
              isActive && "rm-format-choice--active",
            )}
          >
            <div className={cn("flex flex-col", surfaceCardPadding, sectionPanelLead)}>
              <div className="flex items-start justify-between gap-4">
                <div className={sectionLabelHeadlineStack}>
                  <span className={isActive ? subsectionTitle : subsectionTitleMuted}>{data.tag}</span>
                  <span className={cn(textMeta, textGhost)}>{data.tempo}</span>
                </div>
                <span aria-hidden className="rm-format-choice__indicator" />
              </div>

              <p className={cn(textMeta, "m-0", textGhost)}>{data.meta}</p>
              <p className={cn(textCardBody, "m-0 text-pretty")}>{data.summary}</p>
              <p className={cn(textMeta, "m-0", !isActive && textGhost)}>Best for · {data.bestFor}</p>
            </div>
          </button>
        );
      })}
    </div>
  );
}

function FormatOperatingStrip({ mode }: { mode: Mode }) {
  const data = modes[mode];
  const items = [
    ["Format", data.format],
    ["Cadence", data.cadence],
    ["Output", data.output],
  ] as const;

  return (
    <dl className={formatOperatingStrip}>
      {items.map(([label, value]) => (
        <div key={label} className={sectionLabelHeadlineStack}>
          <dt className={cn(textMeta, textGhost)}>{label}</dt>
          <dd className={cn(bodyCopyStrong, "m-0 text-pretty")}>{value}</dd>
        </div>
      ))}
    </dl>
  );
}

function DeliverablesRail({ mode }: { mode: Mode }) {
  const data = modes[mode];

  return (
    <section aria-labelledby={`deliverables-${mode}`}>
      <div className={sectionPanelLead}>
        <h4 id={`deliverables-${mode}`} className={cn("m-0", textMeta, textGhost)}>
          What ships inside
        </h4>
        <p className={cn("m-0", textCardBody, textSubtle)}>Three core deliverables per engagement cycle.</p>
      </div>

      <div className={engageStepsShell}>
        <div className="rm-engage-rail pointer-events-none absolute inset-x-0 hidden md:block" aria-hidden>
          <div className="h-full w-full bg-white/[0.08]" />
          <div className="rm-engage-rail__fill absolute inset-0 origin-left bg-gradient-to-r from-white/45 via-white/25 to-white/10" />
        </div>

        <div className={engageStepsGrid}>
          {data.deliverables.map((item, index) => (
            <dl
              key={item.title}
              role="group"
              aria-label={item.title}
              tabIndex={0}
              className={engageStepItem}
            >
              <span
                aria-hidden
                className="rm-engage-step__dot absolute left-0 z-[1] hidden size-1.5 rounded-full bg-white ring-[3px] ring-black md:block"
              />
              <dt className="flex items-baseline gap-2">
                <span className={engageStepCode}>{String(index + 1).padStart(2, "0")}</span>
                <span className={engageStepTitle}>{item.title}</span>
              </dt>
              <dd className={cn("m-0 max-w-prose", bodyCopy)}>{item.body}</dd>
            </dl>
          ))}
        </div>
      </div>
    </section>
  );
}

function ProofRow({ mode }: { mode: Mode }) {
  const data = modes[mode];

  return (
    <section aria-labelledby={`proof-${mode}`}>
      <div className={sectionPanelLead}>
        <h4 id={`proof-${mode}`} className={cn("m-0", textMeta, textGhost)}>
          Client results
        </h4>
        <p className={cn("m-0", textCardBody, textSubtle)}>Measured outcomes from recent engagements.</p>
      </div>

      <div className={productsProofGrid}>
        {data.proof.map((stat) => (
          <dl key={stat.label} className={cn(productsProofItem, "m-0")}>
            <dt className="rm-stat-hero tabular-nums">{stat.value}</dt>
            <dd className="m-0 flex flex-col gap-3">
              <span className={textLabel}>{stat.label}</span>
              <span className={cn(bodyCopy, "max-w-[28ch] text-pretty")}>{stat.context}</span>
            </dd>
          </dl>
        ))}
      </div>
    </section>
  );
}

/** Split the lead paragraph at its first sentence — gives the eye an entry point before the rest. */
function splitLead(lead: string): [string, string] {
  const match = lead.match(/^(.+?[.!?])\s+(.*)$/s);
  return match ? [match[1], match[2]] : [lead, ""];
}

function FormatOverview({ mode }: { mode: Mode }) {
  const data = modes[mode];
  const [leadHook] = splitLead(data.lead);

  return (
    <AnimatePresence mode="wait" initial={false}>
      <motion.div
        key={mode}
        id={MODE_PANEL_ID}
        role="region"
        aria-labelledby={`mode-tab-${mode}`}
        className={cn("rm-format-panel", productsPanelStack, surfaceCardPadding)}
        variants={modePanelVariants}
        initial="hidden"
        animate="visible"
        exit="exit"
      >
        <div className={engagePanelLead}>
          <p className={cn("m-0", textMeta, textGhost)}>Choose this if</p>
          <p className="m-0 rm-copy-standfirst rm-copy-standfirst--band">{data.fitSignal}</p>
          <p className={cn(bodyCopyStrong, "m-0 text-pretty")}>{data.headline}</p>
          <p className={cn(bodyCopy, "m-0")}>{leadHook}</p>
        </div>

        <FormatOperatingStrip mode={mode} />

        <DeliverablesRail mode={mode} />

        <ProofRow mode={mode} />

        <div className={cn(sectionZoneDividerNested, "flex justify-end")}>
          <Link to="/contact" className={cn(btnPrimary, "group gap-2")}>
            {data.cta.replace(/\s*→$/, "")}
            <BtnArrow />
          </Link>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}

function ComparisonTable() {
  return (
    <div className="rm-comparison-card">
      <table className="rm-comparison-table w-full border-collapse">
        <colgroup>
          <col className="rm-comparison-table__label-col" />
          <col className="rm-comparison-table__value-col" />
          <col className="rm-comparison-table__value-col" />
        </colgroup>
        <thead>
          <tr className={cn("border-b", borderSoft)}>
            <th className="text-left align-middle" scope="col">
              <span className={cn(textMeta, textGhost)}>Decision lens</span>
            </th>
            <th className="text-left align-middle" scope="col">
              <div className={sectionLabelHeadlineStack}>
                <span className={subsectionTitle}>Sprint</span>
                <span className={cn(textCardBody, textSubtle)}>{modes.sprint.tempo}</span>
              </div>
            </th>
            <th className="text-left align-middle" scope="col">
              <div className={sectionLabelHeadlineStack}>
                <span className={subsectionTitle}>Marathon</span>
                <span className={cn(textCardBody, textSubtle)}>{modes.marathon.tempo}</span>
              </div>
            </th>
          </tr>
        </thead>

        <tbody>
          {comparisonRows.map((row) => (
            <tr key={row.label} className={cn("border-b", borderSoft, "last:border-b-0")}>
              <th scope="row" className={cn("text-left align-middle", textMeta, textGhost)}>
                {row.label}
              </th>
              <td data-col="Sprint" className="align-middle">
                <span className={cn(textValue, row.label === "Best for" && "rm-type-body-strong")}>
                  {row.sprint}
                </span>
              </td>
              <td data-col="Marathon" className="align-middle">
                <span className={cn(textValue, row.label === "Best for" && "rm-type-body-strong")}>
                  {row.marathon}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ProductsPage() {
  const reduce = useReducedMotion();
  const [mode, setMode] = useState<Mode>("sprint");
  const hero = {
    tag: "Products",
    titleLines: ["Choose the level of support", "that matches the decision in front of you."] as string[],
    body:
      "Same engine, two tempos. Sprint is for the next hard deadline. Marathon is for the system you need to keep building after it.",
  };

  return (
    <div className="rm-page selection:bg-rm-accent selection:text-black">
      <a href="#main" className="skip-link">
        Skip to content
      </a>
      <PageSectionDots sections={productsPageDots} />
      <SiteHeader variant="dark" overlay />

      <div id="products-top">
        <ServicesHero
          tag={hero.tag}
          titleLines={hero.titleLines}
          body={hero.body}
          bodyClassName={heroStandfirst}
          headingId="products-heading"
          sectionClassName="bg-black"
          align="center"
          ambient={<HeroAmbientImage src={productsHeroAmbient} />}
          scrollCue={<HeroScrollCue />}
          actions={
            <>
              <button
                type="button"
                onClick={() =>
                  document.getElementById("format")?.scrollIntoView({ behavior: reduce ? "auto" : "smooth" })
                }
                className={cn(btnPrimary, "group gap-2")}
              >
                Compare formats
                <BtnArrow className="rotate-90" />
              </button>
              <Link to="/cases" className={cn(btnOutlineOnDark, "group gap-2")}>
                See case studies
                <BtnArrow />
              </Link>
            </>
          }
        />
      </div>

      <main id="main">
        <section
          id="format"
          aria-labelledby="format-heading"
          className={cn(sectionShell, "relative bg-black")}
          style={{ scrollMarginTop: "var(--rm-header-offset)" }}
        >
          <div aria-hidden className="rm-products-glow" />
          <div className={sectionInner}>
            <div className={cn(sectionContentGrid, "items-start")}>
              <div className="md:col-start-1">
                <FramerTag>Engagement formats</FramerTag>
              </div>

              <div className={cn(productsFormatColumn, "md:col-span-2 md:col-start-2")}>
                <div className={sectionHeadlineLead}>
                  <h2 id="format-heading" className={sectionHeadline}>
                    Pick the working rhythm that fits the moment.
                  </h2>
                  <p className={cn(sectionSubheading, "rm-copy-standfirst--band m-0")}>
                    Compare both formats at a glance, then open the detail panel for deliverables,
                    operating model, and proof.
                  </p>
                </div>

                <FormatChoiceCards active={mode} onChange={setMode} />
                <FormatOverview mode={mode} />
              </div>
            </div>
          </div>
        </section>

        <div className="rm-products-tone-bridge" aria-hidden />

        <section
          id="compare"
          aria-labelledby="compare-heading"
          className={cn(sectionShell, "relative bg-black")}
          style={{ scrollMarginTop: "var(--rm-header-offset)" }}
        >
          <div aria-hidden className="rm-products-glow" />
          <div className={sectionInner}>
            <div className={cn(sectionContentGrid, "items-start")}>
              <div className="md:col-start-1">
                <FramerTag>Compare formats</FramerTag>
              </div>

              <div className={cn(productsFormatColumn, "md:col-span-2 md:col-start-2")}>
                <div className={sectionHeadlineLead}>
                  <h2 id="compare-heading" className={sectionHeadline}>
                    One engine, two tempos.
                  </h2>
                  <p className={cn(sectionSubheading, "rm-copy-standfirst--band m-0")}>
                    Sprint points everything at a single deadline. Marathon compounds the same
                    work quarter after quarter. Pick by the decision in front of you, not by which
                    option looks bigger on paper.
                  </p>
                </div>

                <ComparisonTable />

                <div className={sectionActionsInline}>
                  <Link to="/contact" className={cn(btnPrimary, "group gap-2")}>
                    Talk through the fit
                    <BtnArrow />
                  </Link>
                  <Link to="/cases" className={cn(btnOutlineOnDark, "group gap-2")}>
                    See case studies
                    <BtnArrow />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        <ScrollChapter variant="reveal">
          <UnifiedCTA
            title="Not sure which one fits?"
            titleAccent="Let's figure it out together. Book a 30-minute call. We'll ask you three questions and tell you exactly which format makes sense — or why neither does."
            primaryLabel="Book a call"
            primaryTo="/contact"
            secondaryLabel="See case studies"
            secondaryTo="/cases"
          />
        </ScrollChapter>
      </main>

      <SiteFooter />
    </div>
  );
}
