import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { AnimatePresence, motion, useReducedMotion, type Variants } from "framer-motion";

import {
  BtnArrow,
  FramerTag,
  bodyCopy,
  borderSoft,
  btnOutlineOnDark,
  btnPrimary,
  sectionContentGrid,
  sectionHeadline,
  sectionInner,
  sectionShell,
  sectionSubheading,
  subsectionTitle,
  surfaceCardPadding,
  textCardBody,
  textGhost,
  textLabel,
  textMeta,
  textSubtle,
} from "@/components/framer-section";
import { ServicesHero } from "@/components/services-hero";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { SurfaceCard } from "@/components/surface-card";
import { CardContent } from "@/components/ui/card";
import { UnifiedCTA } from "@/components/unified-cta";
import { buildPageHead } from "@/lib/seo";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/products/")({
  head: () => {
    const seo = buildPageHead({
      title: "Products — Sprint & Marathon | R—M",
      description: "Sprint from 4 weeks or Marathon from 2 months.",
      pathname: "/products",
    });
    return {
      meta: seo.meta,
      links: seo.links,
    };
  },
  component: ProductsPage,
});

const modes = {
  sprint: {
    tag: "Sprint",
    meta: "From 4 weeks · tactical retainer",
    headline: "High-impact marketing for fast raises and tight deadlines.",
    summary:
      "Built for a defined push: a raise, launch, or one blocked part of growth that needs a fast reset.",
    lead: "Sprint is a focused engagement with a clear scope and hard deadline. We embed into your workflow, deploy target channel mix, and move fast. You get weekly deliverables and clear data within a flexible monthly setup. Best suited for early-stage founders, growth leads preparing for a raise, and teams with solid traction looking for a breakthrough.",
    cta: "Scope a Sprint →",
    format: "Tactical retainer",
    bestFor: "A defined challenge",
    cadence: "Daily check-ins",
    output: "Fixed deliverables",
    proof: [
      {
        value: "$75 → $30",
        label: "CPL in 30 days",
        context: "Paid acquisition rebuilt within the first month",
      },
      {
        value: "2.7",
        label: "ROAS in the first month",
        context: "Through a locked channel test stack",
      },
      {
        value: "3×",
        label: "Daily lead volume",
        context: "While cutting CPA from $50 to $30",
      },
    ],
    deliverables: [
      {
        title: "Positioning audit & fix",
        body: "We read everything your market sees—landing pages, decks, ads, socials—and rewrite the core pitch that should be doing 80% of the heavy lifting.",
      },
      {
        title: "Channel test stack",
        body: "Three high-probability distribution bets, deployed together over a two-week cycle. Hypothesis, creative, copy, and success metrics fully locked before launch.",
      },
      {
        title: "Conversion system review",
        body: "End-to-end funnel teardown: from first impression to signed deal. We isolate the single choke-point costing you the most and clear it.",
      },
    ],
  },
  marathon: {
    tag: "Marathon",
    meta: "From 2 months · strategic partnership",
    headline: "For founders building a category beyond a product.",
    summary:
      "Built for teams that need an embedded strategic partner shaping message, GTM, and channel system over time.",
    lead: "Marathon is a foundational growth ecosystem. We replace the need for an in-house department to take over the entire function — from core strategy and positioning to long-term multi-channel execution. Built for Series A+ companies, ambitious scale-ups, and teams focusing on long-term growth as a board-level priority.",
    cta: "Start a Marathon →",
    format: "Strategic partnership",
    bestFor: "Full brand build or market entry",
    cadence: "Weekly / Monthly strategy sessions",
    output: "Brand / GTM strategy",
    proof: [
      {
        value: "2.3×",
        label: "Pipeline growth in 6 months",
        context: "Inbound more than doubled on a flat paid budget",
      },
      {
        value: "30–50%",
        label: "Of all MQLs",
        context: "Generated by organic search alone",
      },
      {
        value: "10% → 25%",
        label: "Brand awareness",
        context: "Built through systematic communication",
      },
    ],
    deliverables: [
      {
        title: "Market narrative architecture",
        body: "Your core message should never lose relevance. Every quarter, we analyze and update your positioning to match the current market reality.",
      },
      {
        title: "Finding new growth tracks",
        body: "Every month, we line up fresh channel and creative ideas. We track live performance, filter out the noise, and scale the top performers.",
      },
      {
        title: "Embedded strategic support",
        body: "Continuous C-level support for your launches, fundraises, and pivots. We operate inside your context, working alongside your core team.",
      },
    ],
  },
} as const;

type Mode = keyof typeof modes;

const UNDERLINE_SPRING = { type: "spring", stiffness: 380, damping: 34 } as const;

const modePanelVariants: Variants = {
  hidden: { opacity: 0, y: 18 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.38, ease: [0.22, 1, 0.36, 1] },
  },
  exit: {
    opacity: 0,
    y: -10,
    transition: { duration: 0.18, ease: [0.4, 0, 1, 1] },
  },
};

const heroRise: Variants = {
  hidden: { opacity: 0, y: 22 },
  show: { opacity: 1, y: 0, transition: { duration: 0.8, ease: [0.22, 1, 0.36, 1] } },
};

const MODE_PANEL_ID = "format-panel";

const comparisonRows = [
  {
    label: "Engagement",
    sprint: modes.sprint.meta,
    marathon: modes.marathon.meta,
  },
  {
    label: "Best for",
    sprint: modes.sprint.bestFor,
    marathon: modes.marathon.bestFor,
  },
  {
    label: "Cadence",
    sprint: modes.sprint.cadence,
    marathon: modes.marathon.cadence,
  },
  {
    label: "Output",
    sprint: modes.sprint.output,
    marathon: modes.marathon.output,
  },
  {
    label: "Operating model",
    sprint: modes.sprint.summary,
    marathon: modes.marathon.summary,
  },
] as const;

function ModeSwitcher({ active, onChange }: { active: Mode; onChange: (mode: Mode) => void }) {
  const reduce = useReducedMotion();

  return (
    <div
      role="tablist"
      aria-label="Choose engagement format"
      className="flex flex-wrap items-end gap-x-8 gap-y-1 border-b border-white/10"
    >
      {(["sprint", "marathon"] as const).map((mode) => {
        const isActive = active === mode;
        return (
          <button
            key={mode}
            type="button"
            id={`mode-tab-${mode}`}
            role="tab"
            aria-selected={isActive}
            aria-controls={MODE_PANEL_ID}
            tabIndex={isActive ? 0 : -1}
            onClick={() => onChange(mode)}
            className={cn(
              "relative -mb-px cursor-pointer border-0 bg-transparent p-0 pb-2",
              subsectionTitle,
              "transition-colors duration-300 ease-[cubic-bezier(0.22,1,0.36,1)]",
              "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/25 focus-visible:ring-offset-4 focus-visible:ring-offset-black",
              isActive ? "text-white" : "text-[var(--rm-text-ghost)] hover:text-[var(--rm-text-body)]",
            )}
          >
            {modes[mode].tag}
            {isActive ? (
              <motion.span
                layoutId="products-mode-underline"
                className="absolute inset-x-0 bottom-0 h-px bg-white"
                transition={reduce ? { duration: 0 } : UNDERLINE_SPRING}
              />
            ) : null}
          </button>
        );
      })}
    </div>
  );
}

function DeliverablesRail({ mode }: { mode: Mode }) {
  const data = modes[mode];

  return (
    <div className="flex flex-col gap-4">
      <p className={cn("m-0", textMeta, textGhost)}>What ships inside</p>

      <div className="rm-engage-steps relative pt-6 md:pt-8">
        <div className="rm-engage-rail pointer-events-none absolute inset-x-0 hidden md:block" aria-hidden>
          <div className="h-full w-full bg-white/[0.08]" />
          <div className="rm-engage-rail__fill absolute inset-0 origin-left bg-gradient-to-r from-white/45 via-white/25 to-white/10" />
        </div>

        <div className="grid gap-x-8 gap-y-6 md:grid-cols-3 lg:gap-x-12">
          {data.deliverables.map((item, index) => (
            <dl
              key={item.title}
              role="group"
              aria-label={item.title}
              className={cn(
                "rm-engage-step group/step relative m-0 flex flex-col gap-2 py-5 first:pt-0 md:gap-2 md:py-0",
                "max-md:border-b max-md:last:border-b-0",
                borderSoft,
              )}
            >
              <span
                aria-hidden
                className="rm-engage-step__dot absolute left-0 z-[1] hidden size-1.5 rounded-full bg-white ring-[3px] ring-black md:block"
              />
              <dt className="flex items-baseline gap-2.5">
                <span className={cn(textMeta, textGhost, "rm-engage-step__code")}>
                  {String(index + 1).padStart(2, "0")}
                </span>
                <span className={cn(textMeta, textSubtle, "rm-engage-step__title")}>
                  {item.title}
                </span>
              </dt>
              <dd className={cn("m-0 max-w-[34ch]", textCardBody, textSubtle)}>{item.body}</dd>
            </dl>
          ))}
        </div>
      </div>
    </div>
  );
}

function ProofRow({ mode }: { mode: Mode }) {
  const data = modes[mode];

  const [featured, ...rest] = data.proof;

  return (
    <div className="grid items-start gap-4 sm:grid-cols-[1.4fr_1fr]">
      <SurfaceCard interactive className="min-h-0">
        <CardContent className={cn("flex flex-col gap-0", surfaceCardPadding)}>
          <div className="border-t border-[var(--rm-border-soft)] pt-5">
            <p className={cn(sectionHeadline, "tabular-nums text-white")}>{featured.value}</p>
            <p className={cn(textLabel, "mt-3")}>{featured.label}</p>
            <p className={cn(bodyCopy, "mt-3 max-w-[32ch] text-pretty")}>{featured.context}</p>
          </div>
        </CardContent>
      </SurfaceCard>

      <div className="grid gap-4">
        {rest.map((stat) => (
          <SurfaceCard key={stat.label} interactive className="min-h-0">
            <CardContent className={cn("flex h-full flex-col justify-between gap-0", surfaceCardPadding)}>
              <div className="mt-auto border-t border-[var(--rm-border-soft)] pt-5">
                <p className={cn(subsectionTitle, "tabular-nums")}>{stat.value}</p>
                <p className={cn(textLabel, "mt-3")}>{stat.label}</p>
                <p className={cn(bodyCopy, "mt-3 max-w-[28ch] text-pretty")}>{stat.context}</p>
              </div>
            </CardContent>
          </SurfaceCard>
        ))}
      </div>
    </div>
  );
}

/** Split the lead paragraph at its first sentence — gives the eye an entry point before the rest. */
function splitLead(lead: string): [string, string] {
  const match = lead.match(/^(.+?[.!?])\s+(.*)$/s);
  return match ? [match[1], match[2]] : [lead, ""];
}

function FormatOverview({ mode }: { mode: Mode }) {
  const data = modes[mode];
  const [leadHook, leadRest] = splitLead(data.lead);
  const rows = [
    ["Format", data.format],
    ["Best for", data.bestFor],
    ["Cadence", data.cadence],
    ["Output", data.output],
  ] as const;

  return (
    <AnimatePresence mode="wait" initial={false}>
      <motion.div
        key={mode}
        id={MODE_PANEL_ID}
        role="tabpanel"
        aria-labelledby={`mode-tab-${mode}`}
        className="flex flex-col gap-10 pt-8 md:gap-12"
        variants={modePanelVariants}
        initial="hidden"
        animate="visible"
        exit="exit"
      >
        <div className="grid gap-8 lg:grid-cols-[minmax(0,0.58fr)_minmax(24rem,1.42fr)] lg:gap-12">
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-4">
              <p className={cn("m-0", textMeta, textGhost)}>{data.meta}</p>
              <p className={cn(sectionSubheading, "m-0 max-w-[34ch] text-left text-[var(--rm-text-body)]")}>
                {data.summary}
              </p>
            </div>

            <dl className="flex flex-col border-t border-white/10">
              {rows.map(([label, value]) => (
                <div
                  key={label}
                  className="flex items-baseline justify-between gap-4 border-b border-white/10 py-3 first:pt-4 last:border-b-0"
                >
                  <dt className={cn(textMeta, textGhost)}>{label}</dt>
                  <dd className="m-0 rm-type-body text-right text-white">{value}</dd>
                </div>
              ))}
            </dl>
          </div>

          <div className="flex h-full flex-col gap-6">
            <div className="flex flex-col gap-4">
              <div className="flex flex-col gap-1">
                <p className={cn("m-0", textMeta, textGhost)}>{data.tag}</p>
                <h3 className={cn(subsectionTitle, "max-w-[22ch] text-white")}>{data.headline}</h3>
              </div>
              <p className={cn(sectionSubheading, "m-0 max-w-[38ch] text-white")}>{leadHook}</p>
              {leadRest ? (
                <p className={cn(bodyCopy, "max-w-[42ch] text-[var(--rm-text-subtle)]")}>{leadRest}</p>
              ) : null}
            </div>

            <div className="mt-auto">
              <Link to="/contact" className={cn(btnPrimary, "group gap-2")}>
                {data.cta.replace(/\s*→$/, "")}
                <BtnArrow />
              </Link>
            </div>
          </div>
        </div>

        <ProofRow mode={mode} />

        <DeliverablesRail mode={mode} />
      </motion.div>
    </AnimatePresence>
  );
}

function ComparisonTable({ active }: { active: Mode }) {
  const colTint = (mode: Mode) => (active === mode ? "bg-white/[0.04]" : undefined);

  return (
    <div className="rm-comparison-card overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.03]">
      <table className="rm-comparison-table w-full min-w-[720px] border-collapse">
        <thead>
          <tr className="border-b border-white/10">
            <th className="w-[11rem] md:w-[13rem] px-6 py-7 md:py-8 text-left align-top md:px-8" scope="col">
              <span className={cn(textMeta, textGhost)}>Decision lens</span>
            </th>
            <th
              className={cn("px-6 py-7 md:py-8 text-left align-top md:px-8 transition-colors duration-300", colTint("sprint"))}
              scope="col"
            >
              <div className="flex flex-col gap-2">
                <span className="rm-type-subsection text-white">Sprint</span>
                <span className={cn("rm-type-body", textSubtle)}>Defined push</span>
              </div>
            </th>
            <th
              className={cn("px-6 py-7 md:py-8 text-left align-top md:px-8 transition-colors duration-300", colTint("marathon"))}
              scope="col"
            >
              <div className="flex flex-col gap-2">
                <span className="rm-type-subsection text-white">Marathon</span>
                <span className={cn("rm-type-body", textSubtle)}>Embedded system</span>
              </div>
            </th>
          </tr>
        </thead>

        <tbody>
          {comparisonRows.map((row) => (
            <tr key={row.label} className="border-b border-white/10 last:border-b-0">
              <th
                scope="row"
                className={cn("px-6 py-7 md:py-8 text-left align-top md:px-8", textMeta, textGhost)}
              >
                {row.label}
              </th>
              <td
                data-col="Sprint"
                className={cn("px-6 py-7 md:py-8 align-top md:px-8 transition-colors duration-300", colTint("sprint"))}
              >
                <span className={cn(textCardBody, "text-white", row.label === "Best for" && "rm-type-body-strong")}>
                  {row.sprint}
                </span>
              </td>
              <td
                data-col="Marathon"
                className={cn("px-6 py-7 md:py-8 align-top md:px-8 transition-colors duration-300", colTint("marathon"))}
              >
                <span className={cn(textCardBody, "text-white", row.label === "Best for" && "rm-type-body-strong")}>
                  {row.marathon}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ProductsPage() {
  const reduce = useReducedMotion();
  const [mode, setMode] = useState<Mode>("sprint");
  const hero = {
    tag: "Products",
    titleLines: ["Choose the level of support", "that matches the decision in front of you."] as string[],
    body:
      "Same engine, two tempos. Sprint is for the next hard deadline. Marathon is for the system you need to keep building after it.",
  };

  return (
    <div className="rm-page selection:bg-rm-accent selection:text-black">
      <a href="#main" className="skip-link">
        Skip to content
      </a>
      <SiteHeader variant="dark" overlay />

      <ServicesHero
        tag={hero.tag}
        titleLines={hero.titleLines}
        body={hero.body}
        bodyClassName="md:!w-[46ch] md:!max-w-[46ch]"
        headingId="products-heading"
        sectionClassName="bg-black"
        actions={
          <>
            <button
              type="button"
              onClick={() =>
                document.getElementById("format")?.scrollIntoView({ behavior: reduce ? "auto" : "smooth" })
              }
              className={cn(btnPrimary, "group gap-2")}
            >
              Compare formats
              <BtnArrow className="rotate-90" />
            </button>
            <Link to="/cases" className={cn(btnOutlineOnDark, "group gap-2")}>
              See case studies
              <BtnArrow />
            </Link>
          </>
        }
      />

      <main id="main">
        <section
          id="format"
          aria-labelledby="format-heading"
          className={cn(sectionShell, "relative bg-black")}
          style={{ scrollMarginTop: "var(--rm-header-offset)" }}
        >
          <div aria-hidden className="rm-products-glow" />
          <div className={sectionInner}>
            <div className={cn(sectionContentGrid, "items-start")}>
              <div className="md:col-start-1">
                <FramerTag>Engagement formats</FramerTag>
              </div>

              <div className="flex flex-col gap-6 md:col-span-2 md:col-start-2">
                <div className="flex flex-col gap-6">
                  <h2 id="format-heading" className={cn(sectionHeadline, "max-w-[18ch] text-white")}>
                    Pick the working rhythm that fits the moment.
                  </h2>
                  <p className={cn(sectionSubheading, "m-0 max-w-[48ch] text-[var(--rm-text-body)]")}>
                    Sprint compresses execution into a defined push. Marathon keeps message,
                    channel mix, and decision-making compounding over time.
                  </p>
                </div>

                <ModeSwitcher active={mode} onChange={setMode} />
                <FormatOverview mode={mode} />
              </div>
            </div>
          </div>
        </section>

        <div className="rm-products-tone-bridge" aria-hidden />

        <section
          aria-labelledby="compare-heading"
          className={cn(sectionShell, "relative bg-black")}
        >
          <div aria-hidden className="rm-products-glow" />
          <div className={sectionInner}>
            <div className={cn(sectionContentGrid, "items-start")}>
              <div className="md:col-start-1">
                <FramerTag>Compare formats</FramerTag>
              </div>

              <div className="flex flex-col gap-6 md:col-span-2 md:col-start-2">
                <div className="flex flex-col gap-6">
                  <h2 id="compare-heading" className={cn(sectionHeadline, "max-w-[18ch] text-white")}>
                    One engine, two tempos.
                  </h2>
                  <p className={cn(sectionSubheading, "m-0 max-w-[48ch] text-[var(--rm-text-body)]")}>
                    Sprint points everything at a single deadline. Marathon compounds the same
                    work quarter after quarter. Pick by the decision in front of you, not by which
                    option looks bigger on paper.
                  </p>
                </div>

                <ComparisonTable active={mode} />

                <div className="flex flex-wrap items-center gap-3">
                  <Link to="/contact" className={cn(btnPrimary, "group gap-2")}>
                    Talk through the fit
                    <BtnArrow />
                  </Link>
                  <Link to="/cases" className={cn(btnOutlineOnDark, "group gap-2")}>
                    See case studies
                    <BtnArrow />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div aria-hidden className="rm-products-cta-bridge" />

        <UnifiedCTA
          title="Not sure which one fits?"
          titleAccent="Let's figure it out together. Book a 30-minute call. We'll ask you three questions and tell you exactly which format makes sense — or why neither does."
          primaryLabel="Book a call"
          primaryTo="/contact"
          secondaryLabel="See case studies"
          secondaryTo="/cases"
        />
      </main>

      <SiteFooter />
    </div>
  );
}
